### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by glutamate** [ANovokmet/svelte-gantt#161]
I am trying to build (the iife js file for use in a vanilla js page):

I am on node 16 and latest commit:

```
tomn@Toms-Mac-mini svelte-gantt % git show --summary
commit ffdbd8c3c745be63ed28e8b785c9ab6ba6b01b0e (HEAD -> master, origin/master, origin/HEAD)
Merge: 8babe1f 16bd62a
Author: V-Py <59333024+V-Py@users.noreply.github.com>
Date:   Wed Jan 18 09:41:06 2023 +0100

    Merge pull request #152 from BlueFoxPrime/fixes-multiple-selection-and-more
    
    Fixes multiple selection and more

tomn@Toms-Mac-mini svelte-gantt % node --version    
v16.18.1
```

But i get the following build error:

```
tomn@Toms-Mac-mini svelte-gantt % npm install && node tools/build

up to date, audited 309 packages in 573ms

41 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[rollup-plugin-svelte] Unknown "dev" option. Please use "compilerOptions" for any Svelte compiler configuration.
Error: Unknown object type "asyncfunction"
    at Object._object (/Users/tomn/tmp/svelte-gantt/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23692:17)
    at Object._function (/Users/tomn/tmp/svelte-gantt/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23793:14)
    at Object.dispatch (/Users/tomn/tmp/svelte-gantt/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23659:30)
    at /Users/tomn/tmp/svelte-gantt/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23720:18
    at Array.forEach (<anonymous>)
    at Object._object (/Users/tomn/tmp/svelte-gantt/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23716:21)
    at Object.dispatch (/Users/tomn/tmp/svelte-gantt/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23659:30)
    at /Users/tomn/tmp/svelte-gantt/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23734:23
    at Array.forEach (<anonymous>)
    at Object._array (/Users/tomn/tmp/svelte-gantt/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23733:20)
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Unknown object type "asyncfunction"
    at Object._object (/Users/tomn/tmp/svelte-gantt/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23692:17)
    at Object._function (/Users/tomn/tmp/svelte-gantt/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23793:14)
    at Object.dispatch (/Users/tomn/tmp/svelte-gantt/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23659:30)
    at /Users/tomn/tmp/svelte-gantt/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23720:18
    at Array.forEach (<anonymous>)
    at Object._object (/Users/tomn/tmp/svelte-gantt/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23716:21)
    at Object.dispatch (/Users/tomn/tmp/svelte-gantt/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23659:30)
    at /Users/tomn/tmp/svelte-gantt/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23734:23
    at Array.forEach (<anonymous>)
    at Object._array (/Users/tomn/tmp/svelte-gantt/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23733:20) {
  code: 'PLUGIN_ERROR',
  plugin: 'rpt2',
  hook: 'transform',
  id: '/Users/tomn/tmp/svelte-gantt/src/index.ts',
  watchFiles: [ '/Users/tomn/tmp/svelte-gantt/src/index.ts' ]
}
tomn@Toms-Mac-mini svelte-gantt % 
```

If anyone can show how to build, I can write a Github action so we can get this working in CI

**Comment by V-Py** [comment]
Sorry for the late response, some help on this subject would be appreciated because I can't really help on the iife bugs at the moment, since I didn't build the library and never work on iife build myself

**Comment by christianhugoch** [comment]
@V-Py Hi, can you take a look at my changes? I can run a build with it

**Comment by ANovokmet** [comment]
Managed to reproduce this, in v4.1 iife builds are fixed, additionally, raw svelte components are also packaged.
