### ISSUE TITLE
Dependency error with moment.js

### ISSUE THREAD

**Issue by skyf0l** [ANovokmet/svelte-gantt#43]
```bash
$ npm run dev

> frontend@0.0.1 dev
> svelte-kit dev

Pre-bundling dependencies:
  svelte/store
  svelte
  svelte-gantt
  svelte/animate
  svelte/easing
  (...and 3 more)
(this will be run only when your dependencies or config have changed)
 > node_modules/svelte-gantt/index.js:1:17: error: No matching export in "node_modules/moment/src/moment.js" for import "duration"
    1 │ import moment, { duration } from 'moment';
      ╵                  ~~~~~~~~

> Build failed with 1 error:
node_modules/svelte-gantt/index.js:1:17: error: No matching export in "node_modules/moment/src/moment.js" for import "duration"
Error: Build failed with 1 error:
node_modules/svelte-gantt/index.js:1:17: error: No matching export in "node_modules/moment/src/moment.js" for import "duration"
    at failureErrorWithLog (/home/skyf0l/repos/RoomIt/frontend/node_modules/esbuild/lib/main.js:1493:15)
    at /home/skyf0l/repos/RoomIt/frontend/node_modules/esbuild/lib/main.js:1151:28
    at runOnEndCallbacks (/home/skyf0l/repos/RoomIt/frontend/node_modules/esbuild/lib/main.js:941:63)
    at buildResponseToResult (/home/skyf0l/repos/RoomIt/frontend/node_modules/esbuild/lib/main.js:1149:7)
    at /home/skyf0l/repos/RoomIt/frontend/node_modules/esbuild/lib/main.js:1258:14
    at /home/skyf0l/repos/RoomIt/frontend/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/home/skyf0l/repos/RoomIt/frontend/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/home/skyf0l/repos/RoomIt/frontend/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
```

With my package.json:
```json
{
  "name": "RoomIt",
  "version": "0.0.1",
  "scripts": {
    "dev": "svelte-kit dev",
    "build": "svelte-kit build",
    "preview": "svelte-kit preview",
    "lint": "prettier --ignore-path .gitignore --check --plugin-search-dir=. .",
    "format": "prettier --ignore-path .gitignore --write --plugin-search-dir=. ."
  },
  "devDependencies": {
    "@sveltejs/kit": "next",
    "prettier": "^2.4.1",
    "prettier-plugin-svelte": "^2.4.0",
    "svelte": "^3.34.0"
  },
  "type": "module",
  "dependencies": {
    "@fontsource/fira-mono": "^4.5.0",
    "@lukeed/uuid": "^2.0.0",
    "cookie": "^0.4.1",
    "svelte-gantt": "^3.0.4-beta"
  }
}
```

**Comment by ANovokmet** [comment]
Why is moment in your node_modules but not in your package.json as a dependency? I'm aware this is probably not the source of the error... but maybe it is important for svelte-kit pre-bundling of dependencies?

There was a similar issue with Sapper https://github.com/ANovokmet/svelte-gantt/issues/34

**Comment by ArmanNik** [comment]
Having the same problem with the new version that shouldn't depend on moment.

**Comment by ArmanNik** [comment]
Never mind, the latest npm package is still at the 3.1.1 version, so in my case the error is justified.

**Comment by ANovokmet** [comment]
> Never mind, the latest npm package is still at the 3.1.1 version, so in my case the error is justified.

Sorry, I have published this version on npm now.
